import variant from "@jitl/quickjs-ng-wasmfile-release-sync";
import { loadQuickJs, type SandboxOptions } from "@sebastianwessel/quickjs";

// Load QuickJS WASM once at module init — resource intensive
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const { runSandboxed } = await loadQuickJs(variant as any);

export type BridgeData = Record<string, unknown>;

/** Extra globals to inject into the sandbox context before running user code */
export type SandboxGlobals = Record<string, unknown>;

/**
 * Runs user-supplied JS code in a QuickJS WASM sandbox.
 *
 * Bridge approach: since the sync QuickJS variant doesn't support async host
 * callbacks, we pre-fetch all data on the host side and inject it as a static
 * data module. The 'siliconharbour' module exposes functions that return the
 * pre-fetched data. This means data is fetched before the sandbox runs.
 *
 * For query tool: pass read-only data (events, jobs, etc.)
 * For execute tool: pass read data + sync results
 *
 * The moduleJs string is generated by the caller with the pre-fetched data
 * already baked in as JSON literals.
 *
 * @param code - User JS module with `export default`
 * @param moduleJs - The siliconharbour module JS string with data baked in
 * @param timeoutMs - Kill sandbox after this many ms
 */
export async function runInSandbox(
  code: string,
  moduleJs: string,
  timeoutMs = 5_000,
  extraGlobals: SandboxGlobals = {},
): Promise<{ ok: true; data: unknown } | { ok: false; error: string }> {
  // Wrap bare async arrow functions in export default
  const wrappedCode =
    code.trim().startsWith("async") && !code.includes("export default")
      ? `export default await (${code.trim()})()`
      : code;

  // Build a globals injection prologue — runs before user code
  // Injects extra globals (e.g. __syncResults__) as JSON-serialised values
  const globalsCode = Object.entries(extraGlobals)
    .map(([k, v]) => `globalThis.${k} = ${JSON.stringify(v)};`)
    .join("\n");

  const finalCode = globalsCode ? `${globalsCode}\n${wrappedCode}` : wrappedCode;

  const options: SandboxOptions = {
    allowFetch: false,
    allowFs: false,
    nodeModules: {
      siliconharbour: {
        "index.js": moduleJs,
      },
    },
    executionTimeout: timeoutMs,
  };

  try {
    const result = await runSandboxed(
      async ({ evalCode }) => evalCode(finalCode),
      options,
    );

    if (result.ok) {
      return { ok: true, data: result.data };
    }
    return { ok: false, error: String((result as { error: unknown }).error ?? "Unknown error") };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
}
